/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Business.Admin;
import Business.Professor.Professor;
import UserInterface.Professor.SignIn.ProfessorSignInJPanel;
import UserInterface.Student.SignIn.StudentSignInJPanel;
import java.util.ArrayList;
import java.util.List;
import java.awt.CardLayout;



/**
 *
 * @author JANFAN
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Admin admin;
    public MainJFrame() {
        initComponents();
        
        admin=new Admin();
        
        addBaseData();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        studentSignIn = new javax.swing.JButton();
        professorSignIn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnViewData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(251, 238, 172));
        MainPanel.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(251, 238, 172));

        studentSignIn.setBackground(new java.awt.Color(117, 194, 246));
        studentSignIn.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        studentSignIn.setText("STUDENT");
        studentSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSignInActionPerformed(evt);
            }
        });

        professorSignIn1.setBackground(new java.awt.Color(117, 194, 246));
        professorSignIn1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        professorSignIn1.setText("PROFESSOR");
        professorSignIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorSignIn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN IN");

        btnViewData.setBackground(new java.awt.Color(0, 153, 102));
        btnViewData.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnViewData.setText("View Data");
        btnViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewData, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professorSignIn1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(professorSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnViewData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        MainPanel.add(mainPanel, "mainPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSignInActionPerformed
        // TODO add your handling code here:
        StudentSignInJPanel studentSignInJPanel=new StudentSignInJPanel(admin);
        MainPanel.add(studentSignInJPanel,"studentSignIn");
        CardLayout cardlayout=(CardLayout)MainPanel.getLayout();
        cardlayout.show(MainPanel,"studentSignIn");
    }//GEN-LAST:event_studentSignInActionPerformed

    private void professorSignIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorSignIn1ActionPerformed
        // TODO add your handling code here:
        ProfessorSignInJPanel professorSignInJPanel=new ProfessorSignInJPanel(admin);
        MainPanel.add(professorSignInJPanel,"professorSignIn");
        CardLayout cardlayout=(CardLayout)MainPanel.getLayout();
        cardlayout.show(MainPanel,"professorSignIn");
    }//GEN-LAST:event_professorSignIn1ActionPerformed

    private void btnViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataActionPerformed
        // TODO add your handling code here:
        AdminJPanel panel=new AdminJPanel(admin);
        MainPanel.add(panel,"ViewData");
        CardLayout cardlayout=(CardLayout)MainPanel.getLayout();
        cardlayout.show(MainPanel,"ViewData");
    }//GEN-LAST:event_btnViewDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnViewData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton professorSignIn1;
    private javax.swing.JButton studentSignIn;
    // End of variables declaration//GEN-END:variables

    private void addBaseData() {
        Professor p1=new Professor("111","111");//create new professor
        admin.addProfessor(p1);
        Professor p2=new Professor("222","222");//create new professor
        admin.addProfessor(p2);
        Professor p3=new Professor("333","333");//create new professor
        admin.addProfessor(p3);
        Professor p4=new Professor("444","444");//create new professor
        admin.addProfessor(p4);
        
        
        p1.setName("111");
        p1.setTopic("111");
        p1.setLanguage("111");
        p1.setRegion("111");
        p2.setName("222");
        p2.setTopic("111");
        p2.setLanguage("222");
        p2.setRegion("222");
        p3.setName("333");
        p3.setTopic("333");
        p3.setLanguage("222");
        p3.setRegion("333");
        p4.setName("444");
        p4.setTopic("444");
        p4.setLanguage("444");
        p4.setRegion("111");
        
        
        
    }
}
