/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Professor.Dashboard;
import Business.Admin;
import Business.Professor.Professor;
import UserInterface.Professor.Dashboard.Comment.ProfessorCommentJPanel;
import UserInterface.Professor.Dashboard.Course.ProfessorCourseJPanel;
import UserInterface.Professor.Dashboard.Profile.ProfessorProfileJPanel;
import java.awt.CardLayout;
/**
 *
 * @author JANFAN
 */
public class ProfessorDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorDashboardJPanel
     */
    
    Admin admin;
    Professor professor;
    public ProfessorDashboardJPanel(Professor professor,Admin admin) {
        initComponents();
        this.professor=professor;
        this.admin=admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlArea = new javax.swing.JPanel();
        btnCourse = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnViewComment = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(251, 238, 172));

        splitPane.setBackground(new java.awt.Color(251, 238, 172));
        splitPane.setDividerSize(20);

        controlArea.setBackground(new java.awt.Color(251, 238, 172));

        btnCourse.setBackground(new java.awt.Color(117, 194, 246));
        btnCourse.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCourse.setText("COURSE");
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(117, 194, 246));
        btnProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnProfile.setText("PROFILE");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnSignOut.setBackground(new java.awt.Color(117, 194, 246));
        btnSignOut.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("SIGN OUT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnViewComment.setBackground(new java.awt.Color(117, 194, 246));
        btnViewComment.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnViewComment.setText("COMMENT");
        btnViewComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlAreaLayout = new javax.swing.GroupLayout(controlArea);
        controlArea.setLayout(controlAreaLayout);
        controlAreaLayout.setHorizontalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlAreaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewComment, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlAreaLayout.createSequentialGroup()
                        .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        controlAreaLayout.setVerticalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnViewComment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        splitPane.setLeftComponent(controlArea);

        workArea.setBackground(new java.awt.Color(251, 238, 172));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        // TODO add your handling code here:
       ProfessorCourseJPanel professorCourseJPanel=new ProfessorCourseJPanel(splitPane, admin,professor);
        splitPane.setRightComponent(professorCourseJPanel);
       //NewJPanel newJPanel=new NewJPanel(splitPane, admin,professor);
       //splitPane.setRightComponent(newJPanel);
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        ProfessorProfileJPanel professorProfileJPanel=new ProfessorProfileJPanel(professor);
        splitPane.setRightComponent(professorProfileJPanel);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        CardLayout cardlayout=(CardLayout)this.getParent().getLayout();
        cardlayout.show(this.getParent(),"professorSignIn");
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnViewCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommentActionPerformed
        // TODO add your handling code here:
        ProfessorCommentJPanel professorCommentJPanel = new ProfessorCommentJPanel (professor);
        splitPane.setRightComponent(professorCommentJPanel);
    }//GEN-LAST:event_btnViewCommentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnViewComment;
    private javax.swing.JPanel controlArea;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
