/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Professor.Dashboard.AddCourse;
import Business.Admin;
import Business.Course.Course;
import Business.Professor.Professor;
import UserInterface.Professor.Dashboard.Course.ProfessorCourseJPanel;
import UserInterface.Student.Dashboard.Course.StudentCourseJPanel;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author xupeihan
 */

public class ProfessorAddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorAddJPanel
     */
    JSplitPane splitPane;
    Admin admin;
    Professor professor;
    public ProfessorAddJPanel(JSplitPane splitPane, Admin admin,Professor professor) {
        initComponents();
        this.splitPane=splitPane;
        this.admin = admin;
        this.professor=professor;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourse1 = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblCourseCode = new javax.swing.JLabel();
        txtCourseCode = new javax.swing.JTextField();
        lblCourseCata = new javax.swing.JLabel();
        txtCourseCata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescr = new javax.swing.JTextArea();
        Save = new javax.swing.JButton();
        boxSemester = new javax.swing.JComboBox<>();
        boxYear = new javax.swing.JComboBox<>();
        boxWeekday = new javax.swing.JComboBox<>();
        boxHour = new javax.swing.JComboBox<>();
        lblCourseCata1 = new javax.swing.JLabel();
        txtCourseTopic = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 238, 172));

        lblCourse1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblCourse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourse1.setText("ADD COURSE DETAIL");

        lblCourseName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseName.setText("Course Name:");

        txtCourseName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        lblCourseCode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCode.setText("Course Code:");

        txtCourseCode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        lblCourseCata.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCata.setText("Course Catalog:");

        txtCourseCata.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Semester:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Year:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Hour:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Weekday:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Course Description:");

        txtDescr.setColumns(20);
        txtDescr.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtDescr.setRows(5);
        txtDescr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtDescr);

        Save.setBackground(new java.awt.Color(117, 194, 246));
        Save.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        boxSemester.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        boxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall", "Spring" }));
        boxSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSemesterActionPerformed(evt);
            }
        });

        boxYear.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        boxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025" }));
        boxYear.setToolTipText("");

        boxWeekday.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        boxWeekday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        boxHour.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        boxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00-03:00", "04:00-07:00", "08:00-11:00", "12:00-15:00", "16:00-19:00", "20:00-23:00", "" }));

        lblCourseCata1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCata1.setText("Course Topic:");

        txtCourseTopic.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        btnBack.setBackground(new java.awt.Color(29, 93, 155));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblCourseCata1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(lblCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCourseCata)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblCourseCode))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseCata, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxWeekday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblCourse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCourse1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseCata)
                    .addComponent(txtCourseCata, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseCata1)
                    .addComponent(txtCourseTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(boxWeekday, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Event handler for the "Save" action.
 * This method is called when the user attempts to save course information.
 * It validates input fields and, if they are valid, creates a new course and associates it with the professor.
 *
 * @param evt The action event that triggered this method.
 */
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
          if(professor.getCourseList().size()>=2){
            JOptionPane.showMessageDialog(this,"You have reached max class");
            return;
          }
          
          if(txtCourseCata.getText().isEmpty()||txtCourseName.getText().isEmpty()||
                  txtCourseCode.getText().isEmpty()||txtCourseTopic.getText().isEmpty()||
                  txtDescr.getText().isEmpty()||boxSemester.getSelectedItem().toString().isEmpty()||
                  boxWeekday.getSelectedItem().toString().isEmpty()||
                  boxHour.getSelectedItem().toString().isEmpty()||boxYear.getSelectedItem().toString().isEmpty())
               JOptionPane.showMessageDialog(this, "Course Information are Empty"); //showbox
          else{
                Course course=new Course();
                course.setProfessorName(professor.getName());
                course.setcCatalog(txtCourseCata.getText());
                course.setcName(txtCourseName.getText());
                course.setcCode(txtCourseCode.getText());
                course.setcTopic(txtCourseTopic.getText());
                course.setcDescription(txtDescr.getText());
                course.setSemester(boxSemester.getSelectedItem().toString());
                course.setWeekdays(boxWeekday.getSelectedItem().toString());
                course.setHours(boxHour.getSelectedItem().toString());
                course.setYears(boxYear.getSelectedItem().toString());
                for(Course course1:professor.getCourseList()){
                        if(course.getTime().equals(course1.getTime())){
                                JOptionPane.showMessageDialog(this,"Time conflict");
                                return;
            }
        }
        professor.getCourseList().add(course);
        admin.addCourse(course);
        ProfessorCourseJPanel professorCourseJPanel=new ProfessorCourseJPanel(splitPane, admin,professor);
        splitPane.setRightComponent(professorCourseJPanel);           
          }
    }//GEN-LAST:event_SaveActionPerformed

    private void boxSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSemesterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ProfessorCourseJPanel panel=new ProfessorCourseJPanel(splitPane,admin,professor);
        splitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> boxHour;
    private javax.swing.JComboBox<String> boxSemester;
    private javax.swing.JComboBox<String> boxWeekday;
    private javax.swing.JComboBox<String> boxYear;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse1;
    private javax.swing.JLabel lblCourseCata;
    private javax.swing.JLabel lblCourseCata1;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JTextField txtCourseCata;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseTopic;
    private javax.swing.JTextArea txtDescr;
    // End of variables declaration//GEN-END:variables
}
