/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Student.Dashboard.CourseView;

import Business.Admin;
import Business.Course.Course;
import Business.Student.Student;
import UserInterface.Student.Dashboard.Course.StudentCourseJPanel;
import java.awt.CardLayout;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author xupeihan
 */
public class StudentViewClassJPanel extends javax.swing.JPanel {
    /**
     * Creates new form StudentViewClassJPanel
     */
    Admin admin;
    Course course;
    Student student;
    JSplitPane SplitPane;
    public StudentViewClassJPanel(Course course, Admin admin, Student student,JSplitPane SplitPane) {
        initComponents();
        this.course=course;
        this.admin=admin;
        this.student=student;
        this.SplitPane=SplitPane;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentViewClassJPanel = new javax.swing.JPanel();
        lblCourseName = new javax.swing.JLabel();
        txtcWeekDay = new javax.swing.JTextField();
        lblSemester = new javax.swing.JLabel();
        lblCourseDesc = new javax.swing.JLabel();
        txtcHour = new javax.swing.JTextField();
        lblCourseCode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWaitlist = new javax.swing.JTable();
        lblWeekDay = new javax.swing.JLabel();
        lblCourseCatalog = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCStu = new javax.swing.JTable();
        lblHour = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblWatilist = new javax.swing.JLabel();
        txtcName = new javax.swing.JTextField();
        txtcYear = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblCourseDetail = new javax.swing.JLabel();
        txtcCode = new javax.swing.JTextField();
        txtcDescription = new javax.swing.JTextField();
        lblSemester1 = new javax.swing.JLabel();
        txtCourseTopic = new javax.swing.JTextField();
        txtcCatalog = new javax.swing.JTextField();

        StudentViewClassJPanel.setBackground(new java.awt.Color(251, 238, 172));

        lblCourseName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseName.setText("Course Name:");

        txtcWeekDay.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcWeekDay.setEnabled(false);
        txtcWeekDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcWeekDayActionPerformed(evt);
            }
        });

        lblSemester.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblSemester.setText("Semester:");

        lblCourseDesc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseDesc.setText("Description:");

        txtcHour.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcHour.setEnabled(false);
        txtcHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcHourActionPerformed(evt);
            }
        });

        lblCourseCode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCode.setText("Course Code:");

        tblWaitlist.setBackground(new java.awt.Color(204, 255, 204));
        tblWaitlist.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblWaitlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Student ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWaitlist.setSelectionBackground(new java.awt.Color(0, 51, 51));
        jScrollPane1.setViewportView(tblWaitlist);

        lblWeekDay.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblWeekDay.setText("WeekDay:");

        lblCourseCatalog.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseCatalog.setText("Course Catalog:");

        tblCStu.setBackground(new java.awt.Color(204, 255, 204));
        tblCStu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblCStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Student ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCStu.setSelectionBackground(new java.awt.Color(0, 51, 51));
        jScrollPane2.setViewportView(tblCStu);

        lblHour.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHour.setText("Hour:");

        btnBack.setBackground(new java.awt.Color(29, 93, 155));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblWatilist.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblWatilist.setText("Waitlist:");

        txtcName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcName.setEnabled(false);
        txtcName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcNameActionPerformed(evt);
            }
        });

        txtcYear.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcYear.setEnabled(false);
        txtcYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcYearActionPerformed(evt);
            }
        });

        txtSemester.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtSemester.setEnabled(false);
        txtSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemesterActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblYear.setText("Year:");

        lblCourseDetail.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblCourseDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourseDetail.setText("COURSE DETAIL");

        txtcCode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcCode.setEnabled(false);
        txtcCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcCodeActionPerformed(evt);
            }
        });

        txtcDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcDescription.setEnabled(false);
        txtcDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcDescriptionActionPerformed(evt);
            }
        });

        lblSemester1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblSemester1.setText("Topic:");

        txtCourseTopic.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtCourseTopic.setEnabled(false);

        txtcCatalog.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcCatalog.setEnabled(false);

        javax.swing.GroupLayout StudentViewClassJPanelLayout = new javax.swing.GroupLayout(StudentViewClassJPanel);
        StudentViewClassJPanel.setLayout(StudentViewClassJPanelLayout);
        StudentViewClassJPanelLayout.setHorizontalGroup(
            StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentViewClassJPanelLayout.createSequentialGroup()
                                    .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(lblCourseName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtcName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                                            .addComponent(lblSemester)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSemester, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentViewClassJPanelLayout.createSequentialGroup()
                                            .addComponent(lblCourseCatalog)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtcCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(lblWeekDay)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtcWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                                    .addComponent(lblHour)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtcHour, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                                    .addComponent(lblCourseCode)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtcCode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                                    .addComponent(lblSemester1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCourseTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                                    .addComponent(lblYear)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtcYear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                                    .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCourseDesc)
                                        .addComponent(lblWatilist))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2))))
                            .addComponent(btnBack))))
                .addGap(148, 148, 148))
        );

        StudentViewClassJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCourseTopic, txtSemester, txtcCatalog, txtcCode, txtcHour, txtcName, txtcWeekDay, txtcYear});

        StudentViewClassJPanelLayout.setVerticalGroup(
            StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCourseDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseName)
                            .addComponent(txtcName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemester1)
                            .addComponent(lblCourseCode)
                            .addComponent(txtcCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcHour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourseCatalog)
                            .addComponent(lblWeekDay)
                            .addComponent(txtcWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(StudentViewClassJPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHour)
                            .addComponent(lblYear)
                            .addComponent(lblSemester))))
                .addGap(18, 18, 18)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentViewClassJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWatilist))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        StudentViewClassJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCourseTopic, txtSemester, txtcCatalog, txtcCode, txtcHour, txtcName, txtcWeekDay, txtcYear});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentViewClassJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentViewClassJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcWeekDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcWeekDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcWeekDayActionPerformed

    private void txtcHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcHourActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StudentCourseJPanel panel=new StudentCourseJPanel(SplitPane,admin,student);
        SplitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtcNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcNameActionPerformed

    private void txtcYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcYearActionPerformed

    private void txtSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemesterActionPerformed

    private void txtcCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcCodeActionPerformed

    private void txtcDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcDescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentViewClassJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseCatalog;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseDesc;
    private javax.swing.JLabel lblCourseDetail;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSemester1;
    private javax.swing.JLabel lblWatilist;
    private javax.swing.JLabel lblWeekDay;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblCStu;
    private javax.swing.JTable tblWaitlist;
    private javax.swing.JTextField txtCourseTopic;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtcCatalog;
    private javax.swing.JTextField txtcCode;
    private javax.swing.JTextField txtcDescription;
    private javax.swing.JTextField txtcHour;
    private javax.swing.JTextField txtcName;
    private javax.swing.JTextField txtcWeekDay;
    private javax.swing.JTextField txtcYear;
    // End of variables declaration//GEN-END:variables
/**
 * Display course information in the input fields for editing.
 * This method populates the text fields with the details of the selected course for editing.
 */
    private void displayProduct() {
        txtcName.setText(course.getcName());
        txtcCode.setText(course.getcCode());
        txtcCatalog.setText(course.getcTopic());
        txtCourseTopic.setText(course.getcTopic());
        txtcDescription.setText(course.getcDescription());
        txtSemester.setText(course.getSemesters());
        txtcWeekDay.setText(course.getWeekdays());
        txtcHour.setText(course.getHours());
        txtcYear.setText(course.getYears());
       
    }
 /**
 * Populate tables with student and waitlist information for the selected course.
 * This method populates tables with student and waitlist information for the selected course.
 * It retrieves the student and waitlist details from the course and displays them in the respective tables.
 */
    private void populateTable() {
        
         txtcName.setText(course.getcName());
        txtcCode.setText(course.getcCode());
        txtcCatalog.setText(course.getcCatalog());
        txtCourseTopic.setText(course.getcTopic());
        txtcDescription.setText(course.getcDescription());
        txtSemester.setText(course.getSemesters());
        txtcWeekDay.setText(course.getWeekdays());
        txtcHour.setText(course.getHours());
        txtcYear.setText(course.getYears());
             DefaultTableModel model1 = (DefaultTableModel) tblCStu.getModel();
             model1.setRowCount(0);
             for(Student student: course.getStudentList()){
               Object [] row = new Object[2];
               row[0] = student;
      
               row[1] = student.getStudentID();
               model1.addRow(row);
             }    
                            
             DefaultTableModel model2 = (DefaultTableModel) tblWaitlist.getModel();
             model2.setRowCount(0);
             for(Student student: course.getWaitList()){
               Object [] row = new Object[2];
               row[0] = student;
             
               row[1] = student.getStudentID();
               model2.addRow(row);
               }
    }
}
