/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Student.Dashboard.Comment;
import Business.Admin;
import Business.Professor.Professor;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author xsyyy
 */
public class StudentCommentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentCommentJPanel
     */
    Professor professor;
    Admin admin;
    public StudentCommentJPanel(Professor prodessor, Admin admin) {
        initComponents();
        this.professor = professor;
        this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourse1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        lblComment = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtProfName = new javax.swing.JTextField();
        btnComment = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 238, 172));

        lblCourse1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblCourse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourse1.setText("COMMENT PROFESSOR");

        txtComment.setColumns(20);
        txtComment.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtComment.setRows(5);
        txtComment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtComment);

        lblComment.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblComment.setText("Comment:");

        lbl1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lbl1.setText("Type the professor's name that you want to comment:");

        txtProfName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtProfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfNameActionPerformed(evt);
            }
        });

        btnComment.setBackground(new java.awt.Color(117, 194, 246));
        btnComment.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnComment.setText("Comment");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCourse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl1)
                        .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblComment)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCourse1)
                .addGap(60, 60, 60)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblComment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Event handler for the "Comment" button action.
 * This method is called when the user clicks the "Comment" button to leave a comment for a professor.
 * It retrieves the professor's name and the comment, searches for the professor with the given name in the administrator's list of professors, and adds the comment to the professor's list of comments if found.
 * It also provides appropriate feedback messages.
 *
 * @param evt The action event that triggered this method.
 */
    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        // TODO add your handling code here:
        String name = txtProfName.getText();
        String comment = txtComment.getText();
        boolean professorFound = false;
        for(Professor p:admin.getAllProfessor()){
            if(p.getName().equals(name)){
                p.getComment().add(comment);
                professorFound = true;
                JOptionPane.showMessageDialog(this,"Successfully comment professor!");
                break;
            }
        }
        if(!professorFound){
            JOptionPane.showMessageDialog(this,"Cannot find this professor! Check the name you typed in.");
        }
    }//GEN-LAST:event_btnCommentActionPerformed

    private void txtProfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblCourse1;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtProfName;
    // End of variables declaration//GEN-END:variables
}
