/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Professor.Dashboard.Comment;
import Business.Professor.Professor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xupeihan
 */
public class ProfessorCommentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorCommentJPanel
     */
    Professor professor;
    public ProfessorCommentJPanel(Professor professor) {
        initComponents();
        this.professor = professor;
        popullateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblComments = new javax.swing.JTable();
        lblViewComment = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 238, 172));

        jScrollPane1.setBackground(new java.awt.Color(251, 238, 172));

        tblComments.setBackground(new java.awt.Color(204, 255, 204));
        tblComments.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblComments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComments.setEnabled(false);
        jScrollPane1.setViewportView(tblComments);
        if (tblComments.getColumnModel().getColumnCount() > 0) {
            tblComments.getColumnModel().getColumn(0).setResizable(false);
        }

        lblViewComment.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblViewComment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewComment.setText("VIEW COMMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewComment, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblViewComment)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewComment;
    private javax.swing.JTable tblComments;
    // End of variables declaration//GEN-END:variables
/**
 * Populates the comments table in the user interface with comments from the professor's comment list.
 * This method retrieves comments from the professor's comment list and displays them in the table.
 */
    private void popullateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblComments.getModel();
        model1.setRowCount(0);
        for(String comment1: professor.getComment()){
            Object [] row = new Object[1];
            row[0] = comment1;
            model1.addRow(row);
           }   
    }
}
